# Generated by Django 2.0.2 on 2019-05-25 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='service',
            old_name='first',
            new_name='name',
        ),
        migrations.AddField(
            model_name='section',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Service.Service'),
        ),
    ]
