# Generated by Django 2.0.2 on 2019-05-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_auto_20190525_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.CharField(default='', max_length=30),
        ),
    ]
