# Generated by Django 2.0.2 on 2019-05-25 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_auto_20190525_1430'),
        ('Server', '0002_server_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='service',
        ),
        migrations.AddField(
            model_name='server',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Service.Section'),
            preserve_default=False,
        ),
    ]
