# Generated by Django 2.0.2 on 2019-05-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0003_auto_20190525_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='description',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
    ]
